# SAGAR GUPTA_24-14-12_Modeling & simulation_Assn-2

In [157]:
import numpy as np

## Question no. 1

##### a) Create a variable named var1 that stores an array of numbers from 1 to 30, 
inclusive. Print var1 and its shape. Hint : arange

In [160]:
var1 = np.arange(1,31)
var1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [162]:
np.shape(var1)

(30,)

##### b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [165]:
var2 = np.reshape(var1,(5,6))
var2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [167]:
np.shape(var2)

(5, 6)

##### c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.

In [170]:
var3 = np.reshape(var2,(3,2,5))

In [172]:
var3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [174]:
np.shape(var3)

(3, 2, 5)

##### d) Use two-dimensional array indexing to set the first value in the second row of var2 
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)

In [177]:
var2[1,0] = -1

In [179]:
var2

array([[ 1,  2,  3,  4,  5,  6],
       [-1,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [181]:
var1

array([ 1,  2,  3,  4,  5,  6, -1,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [183]:
var3

array([[[ 1,  2,  3,  4,  5],
        [ 6, -1,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [185]:
# reshape creates a view if the layout of first array is same as the new array (no new memory allocation) 
# smae view means the change in the elements of new array wiil affect the original array too
# reshape can also be a copy if the layout or memory allocation is diffrent then the reshaped array 
# will have no affect on the original aaray

# in this memory is same thats why reshape is a view

##### Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:

##### (i) Sum var3 over its second dimension and print the result.

In [189]:
np.sum(var3,axis=1)

array([[ 7,  1, 11, 13, 15],
       [27, 29, 31, 33, 35],
       [47, 49, 51, 53, 55]])

##### (ii) Sum var3 over its third dimension and print the result.

In [192]:
var3.sum(axis=2)

array([[ 15,  32],
       [ 65,  90],
       [115, 140]])

##### (iii) Sum var3 over both its first and third dimensions and print the result.

In [195]:
var3.sum(axis=(0,2))

array([195, 262])

f) Write code to do the following:

##### (i) Slice out the second row of var2 and print it.

In [202]:
var2[1]

array([-1,  8,  9, 10, 11, 12])

##### (ii) Slice out the last column of var2 using the -1 notation and print it.

In [205]:
var2[:,-1]

array([ 6, 12, 18, 24, 30])

##### (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [208]:
var2[:2,:2]

array([[ 1,  2],
       [-1,  8]])

## Question no. 2

#### a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [218]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
a = a+1
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.

In [231]:
# i am using the previous a that's why matrix start's from 2
b = a.reshape(-1,1)
b + a

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

#### c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )

In [237]:
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ))

In [239]:
data

array([[ 1.80662444,  2.24763931,  5.16164094,  1.20030066,  0.98419222],
       [ 0.97497038,  0.78865725,  1.31801925,  0.27984531,  0.3559853 ],
       [ 0.06736251,  0.39036073,  0.34367988,  0.50224853,  0.80260071],
       [ 0.29801782,  0.23674562,  3.03728329,  1.63623517,  0.48805122],
       [ 5.51035599,  0.52303598,  3.15917149,  0.18839466,  1.45064908],
       [ 1.43965581,  2.83490823,  2.06648746,  1.46853885,  1.79050322],
       [ 0.20364959,  2.35196116,  0.37574091,  0.60008555,  0.64452627],
       [ 1.69348718,  1.06673928,  0.80387053,  0.39546066,  1.32375455],
       [ 0.30352049,  3.50612425,  0.24718213,  0.33957367,  3.55219315],
       [ 1.25910658,  0.58460655,  1.36930782,  1.39978729,  0.38900792],
       [ 1.6866596 ,  0.27639087,  0.92691088,  0.96136316,  1.86102891],
       [ 1.6026321 ,  0.60079999,  0.55768467,  0.61321872,  0.62938301],
       [ 0.09419729,  0.81307964,  1.02942029,  0.28938348,  2.29423194],
       [ 3.50190892,  0.15338189,  3.3

#### d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normal
M.Tech. Data Science and Modelling & Simulate 2 | 2
random variates and exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normal
distribution.

#### e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.

In [243]:
mean = np.mean(data , axis = 0)
variance = np.var(data , axis = 0)

In [245]:
print("mean of the col -->",mean)
print("variance of the col -->",variance)

mean of the col --> [1.2999969  1.61895836 2.15621057 0.90733431 1.67892229]
variance of the col --> [1.26024705 2.0751206  6.2354655  0.64038778 4.85974604]


In [258]:
std = np.std(data ,axis = 0)
std

array([1.12260725, 1.44052789, 2.49709141, 0.80024233, 2.20448317])

#### f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.

In [261]:
data = data - mean

In [265]:
data

array([[ 5.06627546e-01,  6.28680944e-01,  3.00543037e+00,
         2.92966350e-01, -6.94730075e-01],
       [-3.25026516e-01, -8.30301109e-01, -8.38191322e-01,
        -6.27488998e-01, -1.32293699e+00],
       [-1.23263439e+00, -1.22859763e+00, -1.81253070e+00,
        -4.05085776e-01, -8.76321586e-01],
       [-1.00197908e+00, -1.38221274e+00,  8.81072715e-01,
         7.28900860e-01, -1.19087108e+00],
       [ 4.21035910e+00, -1.09592238e+00,  1.00296092e+00,
        -7.18939648e-01, -2.28273216e-01],
       [ 1.39658917e-01,  1.21594986e+00, -8.97231129e-02,
         5.61204541e-01,  1.11580925e-01],
       [-1.09634731e+00,  7.33002799e-01, -1.78046966e+00,
        -3.07248759e-01, -1.03439602e+00],
       [ 3.93490285e-01, -5.52219087e-01, -1.35234005e+00,
        -5.11873654e-01, -3.55167745e-01],
       [-9.96476408e-01,  1.88716589e+00, -1.90902844e+00,
        -5.67760639e-01,  1.87327085e+00],
       [-4.08903162e-02, -1.03435182e+00, -7.86902757e-01,
         4.92452981e-01

In [267]:
normalised = data/std

In [269]:
normalised

array([[ 4.51295450e-01,  4.36424000e-01,  1.20357243e+00,
         3.66097044e-01, -3.15144195e-01],
       [-2.89528252e-01, -5.76386695e-01, -3.35667056e-01,
        -7.84123730e-01, -6.00112083e-01],
       [-1.09801035e+00, -8.52880143e-01, -7.25856768e-01,
        -5.06203887e-01, -3.97517930e-01],
       [-8.92546416e-01, -9.59518208e-01,  3.52839593e-01,
         9.10850171e-01, -5.40204205e-01],
       [ 3.75051834e+00, -7.60778318e-01,  4.01651664e-01,
        -8.98402427e-01, -1.03549539e-01],
       [ 1.24405857e-01,  8.44100189e-01, -3.59310487e-02,
         7.01293249e-01,  5.06154577e-02],
       [-9.76608076e-01,  5.08843185e-01, -7.13017414e-01,
        -3.83944649e-01, -4.69223825e-01],
       [ 3.50514647e-01, -3.83344947e-01, -5.41566097e-01,
        -6.39648313e-01, -1.61111570e-01],
       [-8.87644726e-01,  1.31005161e+00, -7.64500826e-01,
        -7.09485890e-01,  8.49755117e-01],
       [-3.64244183e-02, -7.18036647e-01, -3.15127734e-01,
         6.15379823e-01

In [271]:
np.mean(normalised)

2.2204460492503132e-17

In [273]:
np.var(normalised)

1.0

In [275]:
np.std(normalised)

1.0

# Qustion no. 3

####  A




















nt the
result.

In [286]:
import numpy as np

def vendermonde(N):
    vec = np.arange(N) + 1
    vec = vec.reshape(-1,1)
    b = np.arange(N)
    global vender
    vender = vec**b
    return vender

vendermonde(12)

array([[          1,           1,           1,           1,           1,
                  1,           1,           1,           1,           1,
                  1,           1],
       [          1,           2,           4,           8,          16,
                 32,          64,         128,         256,         512,
               1024,        2048],
       [          1,           3,           9,          27,          81,
                243,         729,        2187,        6561,       19683,
              59049,      177147],
       [          1,           4,          16,          64,         256,
               1024,        4096,       16384,       65536,      262144,
            1048576,     4194304],
       [          1,           5,          25,         125,         625,
               3125,       15625,       78125,      390625,     1953125,
            9765625,    48828125],
       [          1,           6,          36,         216,        1296,
               7776,  

#### B)

In [291]:
#  linear system  vender * X = b
X = np.ones(12)
X = X.T
print(X)
b = np.matmul(vender,X)
b

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([1.20000000e+01, 4.09500000e+03, 2.65720000e+05, 5.59240500e+06,
       6.10351560e+07, 4.35356467e+08, 2.30688120e+09, 1.22713351e+09,
       9.43953692e+08, 3.73692871e+09, 3.10225064e+08, 3.10073456e+09])

#### C)

In [310]:
inv_vender = np.linalg.inv(vender) 

new = np.matmul(inv_vender , b)
new

array([0.99365711, 1.00758362, 0.99868774, 1.00006294, 0.99999857,
       1.00000048, 0.99999993, 1.        , 1.        , 1.        ,
       1.        , 1.        ])

In [305]:
# i expected that the result should be vector X
# but insted of that the value are little diffrent (approximately 1)
# some value are more than 1 and some are less than 1
# first reson i can think is overflow of data as we take vendermonde matrix as 12 x 12 
# last value of matrix got 0 or -ive values 
# other reson is the python use binary conversion before showing any result 
# may be becuse of that

#### D)

In [314]:
np.linalg.solve(vender,b)

array([0.99998827, 1.00002951, 0.99997139, 1.00001427, 0.99999595,
       1.00000068, 0.99999993, 1.        , 1.        , 1.        ,
       1.        , 1.        ])

In [316]:
# becuse python use binary conversion to show the result
# it is more close to what we expected 
# it is more accurte than the previous one

In [319]:
# https://github.com/Frozen-icebar-007/Sagar-Gupta-_-24-14-12/new/main